account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # Обработчики действий со статьями.
    # path('login/', views.user_login, name='login'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', views.dashboard, name='dashboard'),
    # Шаблоны для доступа к обработчикам смены пароля.
    # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # Обработчики восстановления пароля.
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
]

bookmarks/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bookmarks import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('', views.image_list, name='list'),
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('ranking/', views.image_ranking, name='create'),
]

account/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', default='users/default.png')

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)


class Contact(models.Model):
    user_from = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User', related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)


# Динамическое добавление поля following в модель User
User.add_to_class('following',
                  models.ManyToManyField('self',
                                         through=Contact,
                                         related_name='followers',
                                         symmetrical=False))

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

        def clean_password2(self):
            cd = self.cleaned_data
            if cd['password'] != cd['password2']:
                raise forms.ValidationError('Passwords don\'t match.')
            return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')
        labels = {
            "date_of_birth": "Enter your date of birthday",
            "photo": "Select photo",
        }

account/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST

from account.forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileForm
from account.models import Profile, Contact
from actions.models import Action
from actions.utils import create_action
from common.decorators import ajax_required


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponse('Authenticated successfully')
            else:
                return HttpResponse('Disabled account')
        else:
            return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'account/login.html', {'form': form})


@login_required
def dashboard(request):
    # По умолчанию отображаем все действия.
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    if following_ids:
        # Если текущий пользователь подписался на кого-то,
        # отображаем только действия этих пользователей.
        actions = actions.filter(user_id__in=following_ids)
        actions = actions.select_related('user', 'user__profile') \
                         .prefetch_related('target')[:10]
    paginator = Paginator(actions, 8)
    page = request.GET.get('page')
    try:
        actions = paginator.page(page)
    except PageNotAnInteger:
        # Если переданная страница не является числом, возвращаем первую.
        actions = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # Если получили AJAX-запрос с номером страницы, большим, чем их количество, возвращаем пустую страницу.
            return HttpResponse('')
        # Если номер страницы больше, чем их количество, возвращаем последнюю.
        actions = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'actions/action/list_news_ajax.html', {'section': 'dashboard', 'actions': actions})
    return render(request, 'account/dashboard.html', {'section': 'dashboard', 'actions': actions})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            # Создаем нового пользователя, но пока не сохраняем в базу данных.
            new_user = user_form.save(commit=False)
            # Задаем пользователю зашифрованный пароль.
            new_user.set_password(user_form.cleaned_data['password'])
            # Создание профиля пользователя.
            profile = Profile(user=new_user,
                              date_of_birth=profile_form.cleaned_data['date_of_birth'])
            if request.FILES:
                profile.photo = request.FILES['photo']

            # Сохраняем пользователя в базе данных.
            new_user.save()
            profile.save()
            create_action(new_user, 'has created an account')
            return render(request, 'account/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
        profile_form = ProfileForm()
        return render(request, 'account/register.html', {'user_form': user_form, 'profile_form': profile_form, })


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileForm(instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
        else:
            messages.error(request, 'Error updating your profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'account/edit.html', {'user_form': user_form, 'profile_form': profile_form})


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True).exclude(id=request.user.id)
    return render(request, 'account/user/list.html', {'section': 'people', 'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'account/user/detail.html', {'section': 'people', 'user': user})


@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'ok'})

account/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'account/css/base.css' %}" rel="stylesheet">
    <link href="{% static 'account/css/tooltip.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'account/css/menu.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    {% block styles %}{% endblock %}
</head>

<body data-vide-bg="{% static 'account/video/video_back' %}">
    <div id="header">
        <div class="container">
            <div class="inner_header">
                <span class="logo">Bookmarks</span>
                 {% if request.user.is_authenticated %}
                    <div class="hamburger-menu">
                        <input id="menu__toggle" type="checkbox" />
                        <label class="menu__btn" for="menu__toggle">
                            <span></span>
                        </label>
                        <ul class="menu">
                            <li class="{% if section == 'dashboard' %}selected{% endif %}">
                                <a href="{% url 'dashboard' %}">My dashboard</a>
                            </li>
                            <li class="{% if section == 'images' %}selected{% endif %}">
                                <a href="{% url 'images:list' %}">Images</a>
                            </li>
                            <li class="{% if section == 'people' %}selected{% endif %}">
                                <a href="{% url 'user_list' %}">People</a>
                            </li>
                        </ul>
                    </div>
                {% endif %}
                <span class="user {% if user.is_authenticated %}auth{% endif %}">
                    {% if request.user.is_authenticated %}
                        <span class="welcome">Hello {{ request.user.username }},</span>
                        <a href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a href="{% url 'login' %}">Log-in</a>
                    {% endif %}
                </span>
            </div>      
        </div>
    </div>

    <div id="content">
        <div class="container">
            <div class="inner_content">
                <div class="img_overlay"></div>
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li class="center {{ message.tags }}">{{ message|safe }}
                                <a href="#" class="close"><i class="fas fa-times"></i></a>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% block content %}{% endblock %}          
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
    <script src="{% static 'account/js/jquery.vide.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

    {% block scripts %}{% endblock %}
    <script>
        var csrftoken = Cookies.get('csrftoken');
        function csrfSafeMethod(method) {
            // Для этих методов токен не будет подставляться в заголовок.
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        var is_auth = false;
        function user_span() {
            var user_span = $('.user');
            is_auth = user_span.hasClass('auth') ? true : false;
            if($(window).width()<967) {
                if(is_auth) {
                    user_span.remove();
                    $('.menu').append('<li class="user">'+user_span.html()+'</li>');
                }
            }
            else {
                user_span.remove();
                if(is_auth) {
                    $('.inner_header').append('<span class="user auth">'+user_span.html()+'</span>');
                }
                else {
                    $('.inner_header').append('<span class="user">'+user_span.html()+'</span>');
                }
            }
        }

        $(document).ready( function() {
            user_span();
            $(window).resize(user_span);

            $('a.close').click(
                function(e) {
                    e.preventDefault();
                    $(this).parent().remove();
                }
            );
            {% block domready %}{% endblock %}
        });
    </script>
</body>
</html>