bookmarks/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bookmarks import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('', views.image_list, name='list'),
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('ranking/', views.image_ranking, name='create'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from urllib import request

from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify

from .models import Image


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {'url': forms.HiddenInput,}

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title), image_url.rsplit('.', 1)[1].lower())
        # Скачиваем изображение по указанному адресу.
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)
        if commit:
            image.save()
        return image

images/views.py
import redis
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from actions.utils import create_action
from bookmarks import settings
from common.decorators import ajax_required
from images.forms import ImageCreateForm
from images.models import Image


# Подключение к Redis.
r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)

@login_required
def image_create(request):
    if request.method == 'POST':
        # Форма отправлена.
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # Данные формы валидны.
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            # Добавляем пользователя к созданному объекту.
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, 'Image added successfully')
            # Перенаправляем пользователя на страницу сохраненного изображения.
            return redirect(new_item.get_absolute_url())
    else:
        # Заполняем форму данными из GET-запроса.
        form = ImageCreateForm(data=request.GET)
        return render(request, 'images/image/create.html', {'section': 'images', 'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    # Увеличиваем количество просмотров картинки на 1.
    total_views = r.incr('image:{}:views'.format(image.id))
    # Увеличиваем рейтинг картинки на 1.
    r.zincrby('image_ranking', 1, id)
    return render(request, 'images/image/detail.html', {'section': 'images', 'image': image, 'total_views': total_views})


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status': 'ok'})


@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # Если переданная страница не является числом, возвращаем первую.
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # Если получили AJAX-запрос с номером страницы, большим, чем их количество, возвращаем пустую страницу.
            return HttpResponse('')
        # Если номер страницы больше, чем их количество, возвращаем последнюю.
        actions = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'images/image/list_ajax.html', {'section': 'images', 'images': images})
    return render(request, 'images/image/list.html', {'section': 'images', 'images': images})


@login_required
def image_ranking(request):
    # Получаем набор рейтинга картинок.
    image_ranking = r.zrange('image_ranking', 0, 10, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    # Получаем отсортированный список самых популярных картинок.
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request, 'images/image/ranking.html', {'section': 'images', 'most_viewed': most_viewed})

images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}


{% block content %}
    <h1 class="title">Bookmark an image</h1>
    <img src="{{ request.GET.url }}" class="image-preview">
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input class="btn" type="submit" value="Bookmark it!">
    </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ image.title }}{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block content %}
    <h1 class="title">{{ image.title }}</h1>

    {% with total_likes=image.users_like.count users_like=image.users_like.all %}
        <div class="flex">
            {% load thumbnail %}
            {% thumbnail image.image "300" as im %}
                <a href="{{ image.image.url }}">
                    <img src="{{ im.url }}" class="image-detail">
                </a>
            {% endthumbnail %}

            <div class="description">{{ image.description|linebreaks }}</div>
        </div>
        <div class="image-info">
            <span class="count">
                <span class="total">{{ total_likes }}</span>
                like{{ total_likes|pluralize }} <br>
                {{ total_views }} view{{ total_views|pluralize }}
            </span>
            <a href="#" data-id="{{ image.id }}"
               data-action="{% if request.user in users_like %}un{% endif %}like"
               class="{% if request.user in users_like %}un{% endif %}like btn">
                {% if request.user not in users_like %}
                    <i class="fas fa-thumbs-up"></i> Like
                {% else %}
                    <i class="fas fa-thumbs-down"></i> Unlike
                {% endif %}
            </a>

            <div class="image-likes">
                {% for user in users_like|slice:":3" %}
                    <div data-user_id="{{ user.id }}" class="image_like_user tooltip">
                        <img src="{{ user.profile.photo.url }}">
                        <span class="tooltiptext">{{ user.first_name }}</span>
                    </div>
                {% empty %}
                    <div class="no-likes">Nobody likes this image yet.</div>
                {% endfor %}
            </div>
        </div>
    {% endwith %}

{% endblock content %}

{% block domready %}
    $('a.like, a.unlike').click(function(e) {
        e.preventDefault();
        $.post(
            '{% url 'images:like' %}',
            {id: $(this).data('id'), action: $(this).data('action')},
            function(data) {
                if (data['status'] == 'ok') {
                    var previous_action = $('a.like, a.unlike').data('action');

                    // Изменяем переменную действия.
                    $('a.like, a.unlike').data('action', previous_action == 'like' ? 'unlike' : 'like');

                    // Изменяем текст ссылки.
                    $('a.like, a.unlike').html(previous_action == 'like' ? '<i class="fas fa-thumbs-down"></i> Unlike' : '<i class="fas fa-thumbs-up"></i> Like');

                    // Изменяем стиль ссылки.
                    if($('a.like, a.unlike').hasClass('like')) {
                        $('a.like').removeClass('like').addClass('unlike');
                        $('.image-likes').append(
                            `<div data-user_id="{{ request.user.id }}" class="image_like_user tooltip">
                                <img src="{{ request.user.profile.photo.url }}">
                                <span class="tooltiptext">{{ request.user.first_name }}</span>
                            </div>`
                        );
                        $('.no-likes').remove();
                    }
                    else {
                        $('a.unlike').removeClass('unlike').addClass('like');
                        $('div[data-user_id="{{ request.user.id }}"]').remove();
                        if($('.image-likes').html().trim() === '') {
                            $('.image-likes').append(
                                '<div class="no-likes">Nobody likes this image yet.</div>'
                            );
                        }
                    }

                    // Обновляем общее количество лайков.
                    var previous_likes = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'like' ? ++previous_likes : --previous_likes);
                }
            }
        );
    });
{% endblock %}

images/templates/images/image/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Images bookmarked{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'account/css/object_list.css' %}">
{% endblock %}

{% block content %}
    <div class="title center">
        <h1>Images bookmarked</h1>
        <a class="btn" href="{% url 'images:create' %}"><i class="fas fa-star"></i> Most Ranking</a>
    </div>
    <div class="object-list">
        {% include "images/image/list_ajax.html" %}
    </div>
{% endblock %}


{% block scripts %}
    <script src="{% static 'account/js/pagination_ajax.js' %}"></script>
{% endblock %}
{% block domready %}
    pagination_ajax('.object-list');
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
    <div class="object">
        <a href="{{ image.get_absolute_url }}">
            {% thumbnail image.image "300x300" crop="100%" as im %}
                <img src="{{ im.url }}">
            {% endthumbnail %}
            <div class="object_info center">
                {{ image.title }}
            </div>
        </a>
    </div>
{% endfor %}

images/templates/images/image/ranking.html
{% extends "base.html" %}
{% load static %}

{% block title %}Images ranking{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'account/css/object_list.css' %}">
{% endblock %}

{% block content %}
    <h1 class="title center">Images ranking</h1>
    <div class="object-list">
        {% include "images/image/list_ajax.html" with images=most_viewed %}
    </div>
{% endblock %}